# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

#on:
 # release:
  #  types: [created]
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 7
      uses: actions/setup-java@v2
      with:
        java-version: '8.0'
        distribution: 'temurin'
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: jfrog/setup-jfrog-cli@v2  
    - name: JFrog artifactory
      run: jfrog rt ping --url 'https://artifactstore.jfrog.io/artifactory'
      env:
        #ARTIFACTORY_ACCESS_TOKEN: ${{ github.ARTIFACTORY_ACCESS_TOKEN }}
        JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
   
    - uses: jfrog/setup-jfrog-cli@v2 
    - name: Publish to GitHub Packages Apache Maven
      #run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      run: jfrog rt u "target/*.war"
      #run: jf rt ping
      env:
        #GITHUB_TOKEN: ${{ github.token }}
        JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
